"""Initial migration: create all tables

Revision ID: e4a54530f7ca
Revises: 
Create Date: 2025-10-29 15:51:00.662108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a54530f7ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index('idx_video_status', 'videos', ['status'], unique=False)
    op.create_index('idx_video_uploaded_at', 'videos', ['uploaded_at'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_started_at', 'analyses', ['started_at'], unique=False)
    op.create_index('idx_analysis_status', 'analyses', ['status'], unique=False)
    op.create_index('idx_analysis_video_id', 'analyses', ['video_id'], unique=False)
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('emotion', sa.Enum('NEUTRAL', 'HAPPY', 'SERIOUS', 'PASSIONATE', 'CONFIDENT', 'HOPEFUL', name='emotiontype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emotion_analysis_id', 'emotions', ['analysis_id'], unique=False)
    op.create_index('idx_emotion_timestamp', 'emotions', ['timestamp'], unique=False)
    op.create_index('idx_emotion_type', 'emotions', ['emotion'], unique=False)
    op.create_table('gestures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('HAND_RAISE', 'POINTING', 'OPEN_ARMS', 'HAND_GESTURE', name='gesturetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gesture_analysis_id', 'gestures', ['analysis_id'], unique=False)
    op.create_index('idx_gesture_timestamp', 'gestures', ['timestamp'], unique=False)
    op.create_index('idx_gesture_type', 'gestures', ['type'], unique=False)
    op.create_table('key_moments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('EMOTION', 'GESTURE', 'COMBINED', name='keymomenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_moment_analysis_id', 'key_moments', ['analysis_id'], unique=False)
    op.create_index('idx_key_moment_timestamp', 'key_moments', ['timestamp'], unique=False)
    op.create_table('llm_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('main_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rhetorical_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('argument_structure', sa.Text(), nullable=True),
    sa.Column('persuasive_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persuasion_score', sa.Float(), nullable=False),
    sa.Column('overall_tone', sa.Text(), nullable=False),
    sa.Column('transcript_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index('idx_llm_insight_analysis_id', 'llm_insights', ['analysis_id'], unique=False)
    op.create_index('idx_llm_insight_persuasion_score', 'llm_insights', ['persuasion_score'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcript_analysis_id', 'transcripts', ['analysis_id'], unique=False)
    op.create_index('idx_transcript_start_time', 'transcripts', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcript_start_time', table_name='transcripts')
    op.drop_index('idx_transcript_analysis_id', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('idx_llm_insight_persuasion_score', table_name='llm_insights')
    op.drop_index('idx_llm_insight_analysis_id', table_name='llm_insights')
    op.drop_table('llm_insights')
    op.drop_index('idx_key_moment_timestamp', table_name='key_moments')
    op.drop_index('idx_key_moment_analysis_id', table_name='key_moments')
    op.drop_table('key_moments')
    op.drop_index('idx_gesture_type', table_name='gestures')
    op.drop_index('idx_gesture_timestamp', table_name='gestures')
    op.drop_index('idx_gesture_analysis_id', table_name='gestures')
    op.drop_table('gestures')
    op.drop_index('idx_emotion_type', table_name='emotions')
    op.drop_index('idx_emotion_timestamp', table_name='emotions')
    op.drop_index('idx_emotion_analysis_id', table_name='emotions')
    op.drop_table('emotions')
    op.drop_index('idx_analysis_video_id', table_name='analyses')
    op.drop_index('idx_analysis_status', table_name='analyses')
    op.drop_index('idx_analysis_started_at', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('idx_video_uploaded_at', table_name='videos')
    op.drop_index('idx_video_status', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
